version: '3.8'
services:
  postgres_organization:
    container_name: postgres_db_email
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_email
    ports:
      - "5431:5431"
    expose:
      - "5431"
    command:
      - -p 5431
    volumes:
      - volume_postgres_db_email:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 20s
      retries: 10
volumes:
  volume_postgres_db_email:
    external: false